### ISSUE TITLE
Virtua Racing speedometer wrong

### ISSUE THREAD

**Issue by toxieainc** [nukeykt/Nuked-MD-FPGA#13]
Tested via the current official MisterFPGA update, the speedometer needle is showing as artifacty blocks only. The rest of the game seems to work fine.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/MegaDrive_MiSTer/commit/bb904945f6b9c4788d1fb76ea40866c72bd22e85 - This fixes it.
