### ISSUE TITLE
TMSS

### ISSUE THREAD

**Issue by madsonweb** [nukeykt/Nuked-MD-FPGA#2]
I tried to compile but I get this error:
"Error (12152): Can't elaborate user hierarchy "tmss:tmss_""

Which TMSS file are you using?

**Comment by madsonweb** [comment]
Okay I've got it to compile but I am not 100% sure if the file is correctly formatted. Just want to be sure. A little hint would be appreciated.
Thanks in advance!

**Comment by ogamespec** [comment]
You need a normal TMSS ROM dump (2048 bytes), in uint16_t hex format (1024 halfwords), for $readmemh

Something like this:

![image](https://github.com/nukeykt/Nuked-MD-FPGA/assets/5828819/5b9c0006-b7d3-4155-85ab-574899a7fb6a)

**Comment by madsonweb** [comment]
Perfect. Thank you so much!
